cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'telemachus/brew', 'https://telemachus@bitbucket.org/telemachus/brew.git'

cask 'xquartz'

brew 'mas'
brew 'zsh'
brew 'zsh-completions'
brew 'tree'
brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'gradle'
brew 'tig'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'python'
brew 'uncrustify'
brew 'ngrep'
brew 'trash'
brew 'links'

cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'adium'
cask 'atom'
cask 'firefox', args: { appdir: '~/my-apps/Applications' }
cask 'seashore'
cask 'slack'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'p4merge'
cask 'spotify'
cask 'caffeine'
cask 'screenhero'
cask 'robomongo'
cask 'slate'
cask 'dropbox'
cask 'hipchat'
cask 'intellij-idea'
cask 'arduino'
cask 'docker'
cask 'iterm2'

mas 'Xcode', id: 497799835
mas '1Password', id: 443987910
mas 'Telegram', id: 747648890
mas 'Keynote', id: 409183694
mas 'Pages', id: 409201541
mas 'Airmail', id: 918858936
