#!/usr/bin/env bash
#
# bootstrap installs things.
source "$(dirname "$0")/../secrets/dots.sh"
source "$(dirname "$0")/../lib/symlinks.sh"
source "$(dirname "$0")/../emulator/rooms.sh"

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    # shellcheck source=../lib/git-identity.sh
    . "$DOTFILES_ROOT/lib/git-identity.sh"

    local git_credential
    git_credential=$(default_credential_helper)

    local git_authorname git_authoremail

    if load_git_identity_from_secrets; then
      success "loaded git identity from .dot-secrets/git/identity.sh"
      git_authorname="$GIT_AUTHOR_NAME"
      git_authoremail="$GIT_AUTHOR_EMAIL"
    else
      user ' - What is your github author name?'
      read -e git_authorname
      user ' - What is your github author email?'
      read -e git_authoremail
    fi

    render_gitconfig git/gitconfig.symlink.example git/gitconfig.symlink \
      "$git_authorname" "$git_authoremail" "$git_credential"

    success 'gitconfig'
  fi
}


setup_gitconfig

setup_secret_dotfiles
install_dotfiles

setup_rooms

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

echo ''
echo '  All installed!'
