#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# # Run Homebrew through the Brewfile
# This is now done in bin/dot, so we skip it here
# echo "› brew bundle"
# brew bundle

# find the installers and run them iteratively
allDirectories=$(find . -name install.sh | tr "\n" " ")
fileItemArray=($allDirectories)
length=${#fileItemArray[@]}
echo "Running ${length} post-install scripts..."

executed=1
for val in "${fileItemArray[@]}"; do
  app=$(echo "$val" | awk -F'/' '{print $2}' )

  # Show a simple progress indicator and then move to a new line
  # This ensures password prompts appear on their own line
  printf "\r\033[32mProgress: [%s/%s] %s\033[0m\n" "$executed" "$length" "$app"

  # Execute the install script, capturing output in case of errors
  sh -c "${val}" || {
    echo "Error in ${app} installation"
  }

  let "executed++"
done

echo "Post-install scripts completed."
