#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# # Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
allDirectories=$(find . -name install.sh | tr "\n" " ")
fileItemArray=($allDirectories)
length=${#fileItemArray[@]}
echo "There are ${length} post-install instructions."

executed=1
for val in "${fileItemArray[@]}"; do
  app=$(echo "$val" | awk -F'/' '{print $2}' )
  printf "[%s/%s] -> Starting [%s]\n" "$executed" "$length" "$app"
  sh -c "${val}"
  printf "[%s/%s] -> Finished [%s]\n" "$executed" "$length" "$app"
  let "executed++"
done
